travis:
  secure:
    BINSTAR_TOKEN: l35OCZC/gbrzBFkH4GABfZ3rOBFuXLTLBqIyjYP10BQXreB26kRQGKysTvqFB1JLanVdeGr4CFQ8maPNBRe2jAkYzJR9jIFqWdvyiZpMcDVJvSz5WqM3rg4BeqtgifYorUndK19d6VFsJRZ0T0hyhdQOvDZ+QVLliioJ7Ub0LXvJpN9lmtRHoMTqYytJPozs96Rg1uybcYrH+gs7nJ/+NsyVqGjX3ELt4UW587M+p7tu3ORF99iTLKOy2aNGP6IXt/W52hx43U60edYyjfTb2gnZT2rQXyK22TLrSi8sVXTYTd73uwBw9Sy8OSZBybooVfQNVcoZFWDKpOTjaFql/cXSZ7XtrGpeMxx+JInHrWczcmRYDqBwBkYhPxJ3p6JqTktSRPx5KAZYqjFa71ylcjCGB0Rn5O7GSsiwU6qFy8Nnm1/BMPK0BI2MHG5dpUYkrztotn0Brh9AQxNc+T24DfCdNKdp+c1LRdER64wPjGxPlb5Mxg66Wd5+NlkkbJN8669RMjqiTbpPHil4CORppygjUhXrMQ7w2+5nf6+zSrG/bsV43wpwfxQU5ZcLNuKfrb+fDc4Jo3GbkEXPZzwpkETHapeY6U+b/wtD00cBOfOKfI8lO3WNGdOZx9qFczH+ZYGb4kO2w8EM+sZKJRTEkBbLq4oWLwJmhuGsJvkgqkQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
